DROP TABLE IF EXISTS T_USER CASCADE;

CREATE TABLE T_USER
(
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    E_MAIL VARCHAR(150) NOT NULL,

    CONSTRAINT PK_USER_ID PRIMARY KEY (ID)

);

ALTER TABLE T_USER OWNER TO insurance;
INSERT INTO T_USER (NAME, E_MAIL) VALUES ('Carlos', 'email@email.com');
