DROP TABLE IF EXISTS T_USER CASCADE;

CREATE TABLE T_USER 
(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
    E_MAIL VARCHAR(150) NOT NULL,

    CONSTRAINT PK_USER_ID PRIMARY KEY (ID)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO T_USER (NAME, E_MAIL) VALUES ('Carlos', 'email@email.com');
